In [74]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
from sklearn.linear_model import LinearRegression

In [75]:
data = pd.read_csv('Laptop_price.csv')
data

,Brand,Processor_Speed,RAM_Size,Storage_Capacity,Screen_Size,Weight,Price
0,Asus,3.830296,16,512,11.185147,2.641094,17395.093065
1,Acer,2.912833,4,1000,11.311372,3.260012,31607.605919
2,Lenovo,3.241627,4,256,11.853023,2.029061,9291.023542
3,Acer,3.806248,16,512,12.280360,4.573865,17436.728334
4,Acer,3.268097,32,1000,14.990877,4.193472,32917.990718
...,...,...,...,...,...,...,...
995,HP,3.343584,4,1000,12.587095,3.162399,31593.668017
996,Dell,2.780555,8,256,12.679356,3.750265,9149.521832
997,Dell,3.200569,4,512,12.666315,3.392612,16552.404779
998,Asus,1.604182,8,256,11.215581,3.857613,9407.473459
999,Lenovo,1.711980,4,256,16.561498,3.440883,8807.696702

In [76]:
data.isnull().sum()

Brand               0
Processor_Speed     0
RAM_Size            0
Storage_Capacity    0
Screen_Size         0
Weight              0
Price               0
dtype: int64

In [77]:

X = data.drop('Price', axis=1)
Y = data['Price']

In [78]:
# X = pd.get_dummies(X, columns=['Brand'], drop_first=True)
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X['Brand'] = le.fit_transform(X['Brand'])

X

     Brand  Processor_Speed  RAM_Size  Storage_Capacity  Screen_Size    Weight
0        1         3.830296        16               512    11.185147  2.641094
1        0         2.912833         4              1000    11.311372  3.260012
2        4         3.241627         4               256    11.853023  2.029061
3        0         3.806248        16               512    12.280360  4.573865
4        0         3.268097        32              1000    14.990877  4.193472
..     ...              ...       ...               ...          ...       ...
995      3         3.343584         4              1000    12.587095  3.162399
996      2         2.780555         8               256    12.679356  3.750265
997      2         3.200569         4               512    12.666315  3.392612
998      1         1.604182         8               256    11.215581  3.857613
999      4         1.711980         4               256    16.561498  3.440883

[1000 rows x 6 columns]

In [79]:
X_train ,X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.1,random_state=7)

In [80]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [81]:
model = LinearRegression()
model.fit(X_train_scaled, Y_train)

# Predictions
Y_pred = model.predict(X_test_scaled)
Y_pred

array([ 9268.88375651, 32161.70147774, 10349.84756924, 10351.55454826,
        9432.06611121, 18264.47337439, 10439.51347141,  9300.27834277,
       31257.91844452, 17545.81447568,  9930.55884471, 31900.68654523,
       31900.7562099 , 31456.48031243, 31552.61069995,  9132.87187684,
       31686.20645123, 16964.75385828,  9472.10638229,  9859.2969249 ,
        9076.04329512, 31736.00540232,  9173.00541628,  9146.01722321,
        9599.99752062, 17611.27086603, 31444.56080036, 10641.05332046,
       17014.50556186, 33116.67993302, 31856.55572983,  9585.98335622,
       31591.75064855, 16777.76296981, 31929.56509812, 17254.49318853,
       17387.63363922, 16609.19141155,  9149.42039183, 16790.32764108,
       10706.33599906, 16861.97551656, 17203.32800176, 17273.74647656,
       18211.38745233, 32725.90784654, 16631.14895736,  9144.08486939,
        9236.75377539, 18078.55140231, 17722.20796544, 32882.45405666,
       31699.84365928,  9273.61679514, 32934.26987254, 31670.18812837,
       31426.43836669, 31382.51912218, 16887.3880978 ,  8998.84369673,
       31443.08250051, 31873.63988841, 31814.01053499, 16913.11513706,
       31843.29959086, 17375.55273382, 31520.36832535,  9145.66105063,
       31923.17324785, 10799.79877389,  9632.78924944, 10594.74334255,
       17510.2055517 , 16972.60462691,  9753.02970948, 10576.99122169,
       17065.60238755, 16714.92137419, 31603.62826966,  9777.41955784,
        9231.89002402, 31474.16719337, 31853.1953    ,  9436.82766888,
       18379.86522194, 32315.50867701, 31332.96207994, 31536.57549366,
        9812.4404714 ,  9205.33601816, 32150.77352254,  9348.98740612,
        9088.05617915, 17033.99784192,  9243.7295733 , 31767.73551365,
        9149.42369196, 17225.92174574, 32934.62236761, 32801.51480454])

In [82]:

# Predictions
Y_train_pred = model.predict(X_train)
Y_test_pred = model.predict(X_test)

# Train performance
rmse_train = np.sqrt(mean_squared_error(Y_train, Y_train_pred))
r2_train = r2_score(Y_train, Y_train_pred)

print("Train RMSE:", rmse_train)
print("Train R²:", r2_train)

# Test performance
rmse_test = np.sqrt(mean_squared_error(Y_test, Y_test_pred))
r2_test = r2_score(Y_test, Y_test_pred)

print("Test RMSE:", rmse_test)
print("Test R²:", r2_test)

Train RMSE: 6201599.335692973
Train R²: -437755.68085107836
Test RMSE: 6317838.013147792
Test R²: -428583.66312220035

d:\ML_Scikit\project\mobile_price_prediction\mobile\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
d:\ML_Scikit\project\mobile_price_prediction\mobile\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

In [83]:
import joblib

# Save the model
joblib.dump(model, "linear_regression_model.pkl")

# Later, load the model
loaded_model = joblib.load("linear_regression_model.pkl")

# Test prediction
print("Prediction from loaded model:", loaded_model.predict(X_test_scaled[:5]))

Prediction from loaded model: [ 9268.88375651 32161.70147774 10349.84756924 10351.55454826
  9432.06611121]

In [85]:
# Save scaler
joblib.dump(scaler, "scaler.pkl")

# Load scaler
loaded_scaler = joblib.load("scaler.pkl")

joblib.dump(le, "label_encoder.pkl")


# Example: scale new data before prediction
new_data_scaled = loaded_scaler.transform(X_test.iloc[:5])
print("Prediction:", loaded_model.predict(new_data_scaled))

Prediction: [ 9268.88375651 32161.70147774 10349.84756924 10351.55454826
  9432.06611121]