In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

In [7]:
data = pd.read_csv('/content/data.csv')

In [8]:
data.head(5)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

In [11]:
data = data.drop(columns=['country','date','statezip'])

In [12]:
data['yr_renovated'] = np.where(data['yr_renovated'] < data['yr_built'], data['yr_built'], data['yr_renovated'])
df = data.drop(columns=['yr_built','street','waterfront'])

In [13]:
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,view,condition,sqft_above,sqft_basement,yr_renovated,city
0,3.130000e+05,3.0,1.50,1340,7912,1.5,0,3,1340,0,2005,Shoreline
1,2.384000e+06,5.0,2.50,3650,9050,2.0,4,5,3370,280,1921,Seattle
2,3.420000e+05,3.0,2.00,1930,11947,1.0,0,4,1930,0,1966,Kent
3,4.200000e+05,3.0,2.25,2000,8030,1.0,0,4,1000,1000,1963,Bellevue
4,5.500000e+05,4.0,2.50,1940,10500,1.0,0,4,1140,800,1992,Redmond
...,...,...,...,...,...,...,...,...,...,...,...,...
4595,3.081667e+05,3.0,1.75,1510,6360,1.0,0,4,1510,0,1979,Seattle
4596,5.343333e+05,3.0,2.50,1460,7573,2.0,0,3,1460,0,2009,Bellevue
4597,4.169042e+05,3.0,2.50,3010,7014,2.0,0,3,3010,0,2009,Renton
4598,2.034000e+05,4.0,2.00,2090,6630,1.0,0,3,1070,1020,1974,Seattle
4599,2.206000e+05,3.0,2.50,1490,8102,2.0,0,4,1490,0,1990,Covington

In [14]:
X = df.drop(columns=['price'])
y = df['price']

In [24]:
numeric_cols = ['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'view', 'condition', 'sqft_above', 'sqft_basement', 'yr_renovated']
categorical_cols =['city']



preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), [col for col in X.columns if col in numeric_cols]),
        ('cat', OneHotEncoder(handle_unknown='ignore'), [col for col in X.columns if col in categorical_cols])
    ]
)


x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [22]:
x_train

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,view,condition,sqft_above,sqft_basement,yr_renovated,city
1898,4.0,2.50,2770,45514,2.0,0,4,2770,0,1989,Woodinville
1370,4.0,3.00,3720,29043,2.0,0,3,3720,0,1991,Kirkland
3038,4.0,2.50,2810,11120,2.0,0,3,2810,0,1982,Sammamish
2361,4.0,3.75,4030,10800,2.0,0,3,4030,0,2006,Kirkland
156,3.0,2.00,2000,7000,2.0,0,3,2000,0,1986,Seattle
...,...,...,...,...,...,...,...,...,...,...,...
4426,3.0,1.00,1180,5002,1.5,0,3,1180,0,1946,Shoreline
466,4.0,2.00,2520,6000,1.0,0,3,1400,1120,2007,Seattle
3092,3.0,1.00,1150,8145,1.0,0,4,990,160,1958,Shoreline
3772,2.0,1.00,910,2002,1.5,0,3,910,0,2005,Seattle
860,2.0,1.00,1490,3825,1.0,0,3,860,630,1929,Seattle

In [27]:
model_pipeline = Pipeline(steps=[
    ('preprocess', preprocessor),
    # ('model', LinearRegression())
    ('model', RandomForestRegressor(random_state=42))
])

In [28]:
model_pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['bedrooms', 'bathrooms',
                                                   'sqft_living', 'sqft_lot',
                                                   'floors', 'view',
                                                   'condition', 'sqft_above',
                                                   'sqft_basement',
                                                   'yr_renovated']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['city'])])),
                ('model', RandomForestRegressor(random_state=42))])

In [29]:
y_pred = model_pipeline.predict(x_test)

In [30]:
from sklearn.metrics import r2_score
print(f"R-squared: {r2_score(y_test, y_pred)}")

R-squared: 0.04070515287656851